"""Add completed column

Revision ID: 30184f2ef4f3
Revises: 03d8f9052c6e
Create Date: 2025-03-19 14:48:47.967168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30184f2ef4f3'
down_revision = '03d8f9052c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('do', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('do', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
