"""Add order column to DO model

Revision ID: 99229888abd5
Revises: 
Create Date: 2025-02-03 18:29:42.426906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99229888abd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('do', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('do', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
