"""empty message

Revision ID: 03d8f9052c6e
Revises: 99229888abd5
Create Date: 2025-02-03 22:58:32.915227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d8f9052c6e'
down_revision = '99229888abd5'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('do', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_do_list_id', 'list', ['list_id'], ['id'])  # 外部キーに名前を指定


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('do', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('list_id')

    # ### end Alembic commands ###
